# Generated by Django 5.0.3 on 2024-03-12 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
